
server:
  port: 9098

spring:
  jpa:
    generate-ddl: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://52.203.147.52:8761}/eureka/

---
eureka:
  instance:
    hostname: 52.203.147.52
    nonSecurePort: 9098
